baseURL = "https://MoonOnYou.github.io"
languageCode = "en-us"
title = "ONYOU'S  SITE"
theme = "minimal"
disqusShortname = "onyous-blog"

[params]
    author = "onyou"
    description = "공유로 만드는 아름다운 세상"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "ONYOU'S HOME"
    weight = 1

[[menu.main]]
    url = "/Ubuntu/"
    name = "Ubuntu"
    weight = 2

[[menu.main]]
    url = "/Android/"
    name = "Android"
    weight = 3

[[menu.main]]
    url = "/kotlin/"
    name = "kotlin"
    weight = 4

[[menu.main]]
    url = "/English/"
    name = "English"
    weight = 5

[[menu.main]]
    url = "/etc/"
    name = "etc"
    weight = 6



[[menu.icon]]
    url = "mailto:onyou0031@naver.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/MoonOnYou/"
    name = "github"
    weight = 2

