baseURL = "https://MoonOnYou.github.io"
languageCode = "en-us"
title = "ONYOU'S  SITE"
theme = "minimal"
disqusShortname = "onyous-blog"

[params]
    author = "onyou"
    description = "서로의 삽질을 공유로 줄여주는 아름다운 세상"
    githubUsername = "#"
    accent = "pink"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    # css = ["css/us_style.css"]

[[menu.main]]
    url = "/"
    name = "ONYOU'S HOME"
    weight = 1

[[menu.main]]
    url = "/kotlin/"
    name = "kotlin"
    weight = 2

[[menu.main]]
    url = "/python/"
    name = "python"
    weight = 3

[[menu.main]]
    url = "/hugo/"
    name = "hugo"
    weight = 4

[[menu.icon]]
    url = "mailto:onyou0031@naver.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/MoonOnYou/"
    name = "github"
    weight = 2

